# Generated by Django 5.2.9 on 2026-01-05 22:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('seed_idea', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=120)),
                ('tone', models.CharField(blank=True, default='', max_length=120)),
                ('style_notes', models.TextField(blank=True, default='')),
                ('target_word_count', models.PositiveIntegerField(default=80000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutlineNode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('ACT', 'Act'), ('CHAPTER', 'Chapter'), ('SCENE', 'Scene')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('pov', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('beats', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.outlinenode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outline_nodes', to='main.novelproject')),
            ],
            options={
                'ordering': ['project', 'parent_id', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('BIBLE', 'Bible'), ('OUTLINE', 'Outline'), ('SCENE', 'Scene')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('prompt', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('output_text', models.TextField(blank=True, default='')),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='main.novelproject')),
                ('outline_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='main.outlinenode')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryBible',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_md', models.TextField(blank=True, default='')),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bible', to='main.novelproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='')),
                ('voice_notes', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main.novelproject')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_character_project_name')],
            },
        ),
        migrations.CreateModel(
            name='ManuscriptChunk',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('outline_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='main.outlinenode')),
            ],
            options={
                'ordering': ['outline_node', '-version', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('outline_node', 'version'), name='uniq_chunk_outline_node_version')],
            },
        ),
    ]
