# Generated by Django 5.2.9 on 2026-01-06

from django.db import migrations


def renumber_outline(apps, schema_editor):
    NovelProject = apps.get_model("main", "NovelProject")
    OutlineNode = apps.get_model("main", "OutlineNode")

    for project_id in NovelProject.objects.values_list("id", flat=True):
        acts = list(
            OutlineNode.objects.filter(project_id=project_id, node_type="ACT").order_by("order", "created_at", "id")
        )

        for act in acts:
            chapters = list(
                OutlineNode.objects.filter(project_id=project_id, parent_id=act.id, node_type="CHAPTER").order_by(
                    "order", "created_at", "id"
                )
            )

            for idx, chapter in enumerate(chapters, start=1):
                old_order = chapter.order
                old_title = (chapter.title or "").strip()
                chapter.order = idx
                if old_title == f"Chapter {old_order}":
                    chapter.title = f"Chapter {idx}"

            if chapters:
                OutlineNode.objects.bulk_update(chapters, ["order", "title"])

            for chapter in chapters:
                scenes = list(
                    OutlineNode.objects.filter(project_id=project_id, parent_id=chapter.id, node_type="SCENE").order_by(
                        "order", "created_at", "id"
                    )
                )

                for idx, scene in enumerate(scenes, start=1):
                    old_order = scene.order
                    old_title = (scene.title or "").strip()
                    scene.order = idx
                    if old_title == f"Scene {old_order}":
                        scene.title = f"Scene {idx}"

                if scenes:
                    OutlineNode.objects.bulk_update(scenes, ["order", "title"])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(renumber_outline, migrations.RunPython.noop),
    ]

