# Generated by Django 5.2.9 on 2026-01-06

import re

from django.db import migrations


def renumber_outline(apps, schema_editor):
    NovelProject = apps.get_model("main", "NovelProject")
    OutlineNode = apps.get_model("main", "OutlineNode")

    for project_id in NovelProject.objects.values_list("id", flat=True):
        acts = list(
            OutlineNode.objects.filter(project_id=project_id, node_type="ACT").order_by("order", "created_at", "id")
        )

        chapter_number = 0
        scene_number = 0

        acts_to_update = []
        chapters_to_update = []
        scenes_to_update = []

        for act_idx, act in enumerate(acts, start=1):
            if act.order != act_idx:
                act.order = act_idx
                acts_to_update.append(act)

            chapters = list(
                OutlineNode.objects.filter(project_id=project_id, parent_id=act.id, node_type="CHAPTER").order_by(
                    "order", "created_at", "id"
                )
            )

            for ch_idx, chapter in enumerate(chapters, start=1):
                if chapter.order != ch_idx:
                    chapter.order = ch_idx
                    chapters_to_update.append(chapter)

                chapter_number += 1
                current_title = (chapter.title or "").strip()
                if re.fullmatch(r"Chapter \d+", current_title):
                    desired = f"Chapter {chapter_number}"
                    if current_title != desired:
                        chapter.title = desired
                        if chapter not in chapters_to_update:
                            chapters_to_update.append(chapter)

                scenes = list(
                    OutlineNode.objects.filter(project_id=project_id, parent_id=chapter.id, node_type="SCENE").order_by(
                        "order", "created_at", "id"
                    )
                )

                for sc_idx, scene in enumerate(scenes, start=1):
                    if scene.order != sc_idx:
                        scene.order = sc_idx
                        scenes_to_update.append(scene)

                    scene_number += 1
                    current_scene_title = (scene.title or "").strip()
                    if re.fullmatch(r"Scene \d+", current_scene_title):
                        desired = f"Scene {scene_number}"
                        if current_scene_title != desired:
                            scene.title = desired
                            if scene not in scenes_to_update:
                                scenes_to_update.append(scene)

        if acts_to_update:
            OutlineNode.objects.bulk_update(acts_to_update, ["order"])
        if chapters_to_update:
            OutlineNode.objects.bulk_update(chapters_to_update, ["order", "title"])
        if scenes_to_update:
            OutlineNode.objects.bulk_update(scenes_to_update, ["order", "title"])


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_renumber_outline"),
    ]

    operations = [
        migrations.RunPython(renumber_outline, migrations.RunPython.noop),
    ]

