# Generated by Django 5.2.9 on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_renumber_outline_global_titles"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlinenode",
            name="structure_json",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="outlinenode",
            name="rendered_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]

