# Generated by Django 5.2.9 on 2026-01-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_outline_node_structure_render"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="gender",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AddField(
            model_name="character",
            name="personality",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="character",
            name="appearance",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="character",
            name="background",
            field=models.TextField(blank=True, default=""),
        ),
    ]

