# Generated by Django 5.2.9 on 2026-01-07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_character_structured_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("objects_map", models.JSONField(blank=True, default=dict)),
                ("project", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="locations", to="main.novelproject")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("project", "name"), name="uniq_location_project_name"),
        ),
    ]
