# Generated by Django 5.2.9 on 2026-01-07 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_location_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='portrait_data_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
