# Generated by Django 5.2.9 on 2026-01-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_character_portrait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='portrait_data_url',
        ),
    ]
