# Generated by Django 5.2.9 on 2026-01-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_existing_projects_to_first_user(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    UserModel = apps.get_model(app_label, model_name)
    NovelProject = apps.get_model("main", "NovelProject")

    first_user = UserModel.objects.order_by("id").first()
    if first_user:
        NovelProject.objects.filter(owner__isnull=True).update(owner=first_user)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_character_portrait"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="novelproject",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="novel_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_existing_projects_to_first_user, migrations.RunPython.noop),
    ]

