# Generated by Django 5.2.9 on 2026-01-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_character_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="outlinenode",
            name="characters",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
