# Generated by Django 5.2.9 on 2026-01-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_character_portrait_data_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="image_data_url",
            field=models.TextField(blank=True, default=""),
        ),
    ]
