# Generated by Django 5.2.9 on 2026-03-19 21:56

from django.db import migrations, models


def create_and_backfill_root_locations(apps, schema_editor):
    NovelProject = apps.get_model("main", "NovelProject")
    Location = apps.get_model("main", "Location")

    for project in NovelProject.objects.all().iterator():
        locations = list(Location.objects.filter(project=project).order_by("created_at", "id"))
        root = None

        for loc in locations:
            if loc.is_root:
                root = loc
                break

        if root is None:
            for loc in locations:
                if loc.parent_id is None and loc.name == "World":
                    root = loc
                    break

        if root is None and locations:
            root = Location.objects.create(project=project, name="World", parent=None, is_root=True)
        elif root is None:
            root = Location.objects.create(project=project, name="World", parent=None, is_root=True)
        else:
            root.parent_id = None
            root.is_root = True
            root.save(update_fields=["parent", "is_root"])

        for loc in locations:
            if loc.id == root.id:
                continue
            update_fields = []
            if loc.is_root:
                loc.is_root = False
                update_fields.append("is_root")
            if loc.parent_id is None:
                loc.parent_id = root.id
                update_fields.append("parent")
            if update_fields:
                loc.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_location_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_and_backfill_root_locations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_root', True)), fields=('project',), name='uniq_root_location_per_project'),
        ),
    ]
