# Generated by Django 5.2.9 on 2026-03-20 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_location_is_root_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
