# Generated by Django 5.2.9 on 2026-03-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_processedstripeevent_usersubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabledTextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['model_name'],
            },
        ),
    ]
