# Generated by Django 5.2.9 on 2026-03-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_disabledtextmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisabledTextModel',
        ),
    ]
