# Generated by Django 5.2.9 on 2026-04-08 07:29

import django.db.models.deletion
import main.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_delete_disabledtextmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBibleDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=main.models.story_bible_pdf_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('extracted_text_chars', models.PositiveIntegerField(default=0)),
                ('story_bible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.storybible')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
