# Generated by Django 5.2.9 on 2026-04-09 00:29

import django.db.models.deletion
import django.utils.timezone
import main.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_storybibledocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('source_type', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(blank=True, default='', max_length=40)),
                ('currency', models.CharField(blank=True, default='GBP', max_length=12)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('seller_name', models.CharField(blank=True, default=main.models.default_invoice_seller_name, max_length=255)),
                ('seller_email', models.CharField(blank=True, default=main.models.default_invoice_seller_email, max_length=255)),
                ('seller_address', models.TextField(blank=True, default='')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=255)),
                ('buyer_email', models.CharField(blank=True, default='', max_length=255)),
                ('buyer_address', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('subtotal_amount', models.IntegerField(default=0)),
                ('tax_amount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('subscription_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='main.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
