# Generated by Django 5.2.9 on 2026-04-09 00:56

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_billinginvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('company_name', models.CharField(blank=True, default=main.models.default_invoice_seller_name, max_length=255)),
                ('company_email', models.CharField(blank=True, default=main.models.default_invoice_seller_email, max_length=255)),
                ('company_address', models.TextField(blank=True, default='')),
                ('company_tax_id', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'verbose_name': 'Billing company profile',
                'verbose_name_plural': 'Billing company profile',
            },
        ),
    ]
