# Generated by Django 5.2.9 on 2026-04-16 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_outlinenode_draft_review_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneCriticReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scene_title_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('overall_assessment', models.TextField(blank=True, default='')),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('improvements_vs_previous', models.TextField(blank=True, default='')),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('source_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_truncated', models.BooleanField(default=False)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critic_reviews', to='main.outlinenode')),
            ],
            options={
                'ordering': ['-reviewed_at', '-created_at', '-id'],
            },
        ),
    ]
