# Generated by Django 5.2.9 on 2026-04-22 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicCharacter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, default='', max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('costume_notes', models.TextField(blank=True, default='')),
                ('visual_notes', models.TextField(blank=True, default='')),
                ('voice_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComicIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('theme', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('SCRIPTING', 'Scripting'), ('REVIEW', 'Review'), ('READY', 'Ready')], default='PLANNING', max_length=20)),
                ('planned_page_count', models.PositiveIntegerField(default=22)),
                ('opening_hook', models.TextField(blank=True, default='')),
                ('closing_hook', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComicLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('visual_notes', models.TextField(blank=True, default='')),
                ('continuity_notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComicPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('page_role', models.CharField(choices=[('OPENING', 'Opening'), ('STORY', 'Story'), ('TURN', 'Turn'), ('SPLASH', 'Splash'), ('CLIMAX', 'Climax'), ('CLIFFHANGER', 'Cliffhanger')], default='STORY', max_length=20)),
                ('layout_type', models.CharField(choices=[('STANDARD', 'Standard'), ('GRID', 'Grid'), ('SPLASH', 'Splash'), ('WIDESCREEN', 'Widescreen'), ('DECOMPRESSED', 'Decompressed')], default='STANDARD', max_length=20)),
                ('page_turn_hook', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='comic_book.comicissue')),
            ],
            options={
                'ordering': ['page_number', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComicPanel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('panel_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('shot_type', models.CharField(choices=[('FULL', 'Full'), ('WIDE', 'Wide'), ('MEDIUM', 'Medium'), ('CLOSE', 'Close'), ('EXTREME_CLOSE', 'Extreme close'), ('INSERT', 'Insert')], default='MEDIUM', max_length=20)),
                ('focus', models.CharField(blank=True, default='', max_length=160)),
                ('action', models.TextField(blank=True, default='')),
                ('dialogue', models.TextField(blank=True, default='')),
                ('caption', models.TextField(blank=True, default='')),
                ('sfx', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('characters', models.ManyToManyField(blank=True, related_name='panels', to='comic_book.comiccharacter')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='comic_book.comiclocation')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='comic_book.comicpage')),
            ],
            options={
                'ordering': ['panel_number', 'created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ComicProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('logline', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=120)),
                ('tone', models.CharField(blank=True, default='', max_length=120)),
                ('target_audience', models.CharField(blank=True, default='', max_length=120)),
                ('art_style_notes', models.TextField(blank=True, default='')),
                ('format_notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='comiclocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='comic_book.comicproject'),
        ),
        migrations.AddField(
            model_name='comicissue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='comic_book.comicproject'),
        ),
        migrations.AddField(
            model_name='comiccharacter',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='comic_book.comicproject'),
        ),
        migrations.CreateModel(
            name='ComicBible',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('premise', models.TextField(blank=True, default='')),
                ('world_rules', models.TextField(blank=True, default='')),
                ('visual_rules', models.TextField(blank=True, default='')),
                ('continuity_rules', models.TextField(blank=True, default='')),
                ('cast_notes', models.TextField(blank=True, default='')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bible', to='comic_book.comicproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='comicproject',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_comic_project_owner_slug'),
        ),
        migrations.AddConstraint(
            model_name='comiclocation',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_comic_location_project_name'),
        ),
        migrations.AddConstraint(
            model_name='comicissue',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='uniq_comic_issue_project_number'),
        ),
        migrations.AddConstraint(
            model_name='comiccharacter',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_comic_character_project_name'),
        ),
    ]
