# Generated by Django 5.2.9 on 2026-04-29 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_book', '0009_rename_canvas_to_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicObject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True, default='')),
                ('visual_notes', models.TextField(blank=True, default='')),
                ('continuity_notes', models.TextField(blank=True, default='')),
                ('image_data_url', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_objects', to='comic_book.comicproject')),
            ],
            options={
                'ordering': ['name', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'name'), name='uniq_comic_object_project_name')],
            },
        ),
    ]
