# Generated by Django 5.2.9 on 2026-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_book', '0010_comicobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpanelnode',
            name='referenced_objects',
            field=models.ManyToManyField(blank=True, related_name='panel_nodes', to='comic_book.comicobject'),
        ),
    ]
