from django.urls import path

from . import views

app_name = "comic_book"

urlpatterns = [
    path("", views.ComicBookHomeView.as_view(), name="index"),
    path("projects/new/", views.ComicProjectCreateView.as_view(), name="project-create"),
    path("projects/<slug:slug>/", views.ComicProjectDashboardView.as_view(), name="project-dashboard"),
    path("projects/<slug:slug>/download/", views.download_project_pdf, name="project-download"),
    path("projects/<slug:slug>/edit/", views.ComicProjectUpdateView.as_view(), name="project-edit"),
    path("projects/<slug:slug>/delete/", views.ComicProjectDeleteView.as_view(), name="project-delete"),
    path("projects/<slug:slug>/bible/", views.ComicBibleUpdateView.as_view(), name="bible-edit"),
    path("projects/<slug:slug>/bible/brainstorm/", views.brainstorm_bible, name="bible-brainstorm"),
    path("projects/<slug:slug>/bible/add-details/", views.add_bible_details, name="bible-add-details"),
    path("projects/<slug:slug>/characters/", views.ComicCharacterListView.as_view(), name="character-list"),
    path("projects/<slug:slug>/characters/brainstorm/", views.brainstorm_character, name="character-brainstorm"),
    path("projects/<slug:slug>/characters/add-details/", views.add_character_details, name="character-add-details"),
    path("projects/<slug:slug>/characters/faces/preview/", views.preview_character_faces, name="character-faces-preview"),
    path("projects/<slug:slug>/characters/full-body/preview/", views.preview_character_full_body, name="character-full-body-preview"),
    path("projects/<slug:slug>/characters/new/", views.ComicCharacterCreateView.as_view(), name="character-create"),
    path("projects/<slug:slug>/characters/<uuid:pk>/faces/", views.generate_character_faces, name="character-faces"),
    path("projects/<slug:slug>/characters/<uuid:pk>/full-body/", views.generate_character_full_body, name="character-full-body"),
    path("projects/<slug:slug>/characters/<uuid:pk>/edit/", views.ComicCharacterUpdateView.as_view(), name="character-edit"),
    path("projects/<slug:slug>/characters/<uuid:pk>/delete/", views.ComicCharacterDeleteView.as_view(), name="character-delete"),
    path("projects/<slug:slug>/locations/", views.ComicLocationListView.as_view(), name="location-list"),
    path("projects/<slug:slug>/locations/brainstorm/", views.brainstorm_location, name="location-brainstorm"),
    path("projects/<slug:slug>/locations/add-details/", views.add_location_details, name="location-add-details"),
    path("projects/<slug:slug>/locations/image/preview/", views.preview_location_image, name="location-image-preview"),
    path("projects/<slug:slug>/locations/new/", views.ComicLocationCreateView.as_view(), name="location-create"),
    path("projects/<slug:slug>/locations/<uuid:pk>/edit/", views.ComicLocationUpdateView.as_view(), name="location-edit"),
    path("projects/<slug:slug>/locations/<uuid:pk>/delete/", views.ComicLocationDeleteView.as_view(), name="location-delete"),
    path("projects/<slug:slug>/objects/", views.ComicObjectListView.as_view(), name="object-list"),
    path("projects/<slug:slug>/objects/brainstorm/", views.brainstorm_object, name="object-brainstorm"),
    path("projects/<slug:slug>/objects/add-details/", views.add_object_details, name="object-add-details"),
    path("projects/<slug:slug>/objects/image/preview/", views.preview_object_image, name="object-image-preview"),
    path("projects/<slug:slug>/objects/new/", views.ComicObjectCreateView.as_view(), name="object-create"),
    path("projects/<slug:slug>/objects/<uuid:pk>/edit/", views.ComicObjectUpdateView.as_view(), name="object-edit"),
    path("projects/<slug:slug>/objects/<uuid:pk>/delete/", views.ComicObjectDeleteView.as_view(), name="object-delete"),
    path("projects/<slug:slug>/issues/brainstorm/", views.brainstorm_issue, name="issue-brainstorm"),
    path("projects/<slug:slug>/issues/add-details/", views.add_issue_details, name="issue-add-details"),
    path("projects/<slug:slug>/issues/swap/", views.swap_issues, name="issue-swap"),
    path("projects/<slug:slug>/issues/new/", views.ComicIssueCreateView.as_view(), name="issue-create"),
    path("projects/<slug:slug>/issues/<uuid:pk>/", views.ComicIssueWorkspaceView.as_view(), name="issue-workspace"),
    path("projects/<slug:slug>/issues/<uuid:pk>/edit/", views.ComicIssueUpdateView.as_view(), name="issue-edit"),
    path("projects/<slug:slug>/issues/<uuid:pk>/delete/", views.ComicIssueDeleteView.as_view(), name="issue-delete"),
    path("projects/<slug:slug>/issues/<uuid:pk>/export/", views.ComicIssueExportView.as_view(), name="issue-export"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/new/", views.ComicPageCreateView.as_view(), name="page-create"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:pk>/brainstorm/", views.brainstorm_page, name="page-brainstorm"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:pk>/add-details/", views.add_page_details, name="page-add-details"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:pk>/edit/", views.ComicPageUpdateView.as_view(), name="page-edit"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:pk>/delete/", views.ComicPageDeleteView.as_view(), name="page-delete"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:pk>/shift/", views.shift_page, name="page-shift"),
    path(
        "projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panel/<str:panel_key>/brainstorm/",
        views.brainstorm_panel_node,
        name="panel-node-brainstorm",
    ),
    path(
        "projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panel/<str:panel_key>/add-details/",
        views.add_panel_node_details,
        name="panel-node-add-details",
    ),
    path(
        "projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panel/<str:panel_key>/generate/",
        views.generate_panel_node_image,
        name="panel-node-generate",
    ),
    path(
        "projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panel/<str:panel_key>/quick-prompt/",
        views.quick_prompt_panel_node_image,
        name="panel-node-quick-prompt",
    ),
    path(
        "projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panel/<str:panel_key>/quick-prompt/accept/",
        views.accept_quick_prompt_panel_node_image,
        name="panel-node-quick-prompt-accept",
    ),
    path(
        "projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panel/<str:panel_key>/quick-prompt/reject/",
        views.reject_quick_prompt_panel_node_image,
        name="panel-node-quick-prompt-reject",
    ),
    path(
        "projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panel/<str:panel_key>/edit/",
        views.ComicPanelNodeUpdateView.as_view(),
        name="panel-node-edit",
    ),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panels/new/", views.ComicPanelCreateView.as_view(), name="panel-create"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panels/<uuid:pk>/edit/", views.ComicPanelUpdateView.as_view(), name="panel-edit"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panels/<uuid:pk>/delete/", views.ComicPanelDeleteView.as_view(), name="panel-delete"),
    path("projects/<slug:slug>/issues/<uuid:issue_pk>/pages/<uuid:page_pk>/panels/<uuid:pk>/shift/", views.shift_panel, name="panel-shift"),
]
